tools/check_isr_storage: Add non-interactive mode
- Add -q option to check_isr_storage, which prints the discovered storage
type on stdout rather than displaying a notification

diff --git a/tools/src/check_isr_storage b/tools/src/check_isr_storage
--- a/tools/src/check_isr_storage
+++ b/tools/src/check_isr_storage
@@ -18,21 +18,44 @@
 
 ROOT=/home
 
-if ! mountpoint -q $ROOT ; then
-	notify-send -u critical -t 0 -c device.error -i gtk-dialog-error \
-		"Can't store parcel data" \
-		"Could not locate a suitable storage device for ISR parcel data.  Resuming a parcel is inadvisable."
-	exit 0
-fi
+detect() {
+	if ! mountpoint -q $ROOT ; then
+		echo "none"
+	elif df -P $ROOT | grep -q scratch-home ; then
+		echo "transient"
+	else
+		echo "persistent"
+	fi
+}
 
-free_gb=$(($(df -P $ROOT | awk '!/Filesystem/ {print $4}') >> 20))
-if df -P $ROOT | grep -q scratch-home ; then
-	short="Using transient parcel storage"
-	long="Found $free_gb GiB of transient parcel storage.  Parcel data will become inaccessible after the system is shut down."
+notify() {
+	free_gb=$(($(df -P $ROOT | awk '!/Filesystem/ {print $4}') >> 20))
+	case "$1" in
+	transient)
+		short="Using transient parcel storage"
+		long="Found $free_gb GiB of transient parcel storage.  Parcel data will become inaccessible after the system is shut down."
+		;;
+	persistent)
+		short="Using persistent parcel storage"
+		long="Found persistent parcel storage with $free_gb GiB free.  Do not unplug the boot device until the system is shut down."
+		;;
+	none)
+		notify-send -u critical -t 0 -c device.error \
+			-i gtk-dialog-error "Can't store parcel data" \
+			"Could not locate a suitable storage device for ISR parcel data.  Resuming a parcel is inadvisable."
+		return
+		;;
+	esac
+	notify-send -u low -c device -i gtk-harddisk -t 15000 "$short" "$long"
+}
+
+type=`detect`
+if [ "$1" = "-q" ] ; then
+	echo "$type"
+elif [ -n "$1" ] ; then
+	echo "Usage: $0 [-q]"
+	exit 1
 else
-	short="Using persistent parcel storage"
-	long="Found persistent parcel storage with $free_gb GiB free.  Do not unplug the boot device until the system is shut down."
+	notify "$type"
 fi
-notify-send -u low -c device -i gtk-harddisk -t 15000 "$short" "$long"
-
 exit 0
